# Alacritty configuration
# Colors are imported from pywal

general.import = ["~/.cache/wal/colors-alacritty.toml"]

[window]
padding.x = 10
padding.y = 10
decorations = "full"
opacity = 0.92

[font]
size = 8.0

[font.normal]
family = "JetBrains Mono"
style = "Regular"

[font.bold]
family = "JetBrains Mono"
style = "Bold"

[font.italic]
family = "JetBrains Mono"
style = "Italic"

[cursor]
style.shape = "Block"
style.blinking = "Off"

[selection]
save_to_clipboard = true
